version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ka*dj#D23Aff2

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080